In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df[df['Review Rating'].isnull()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
38,39,29,Male,Dress,Clothing,37,Florida,M,Red,Winter,NaN,Yes,2-Day Shipping,Yes,Yes,44,Venmo,Every 3 Months
50,51,49,Male,Blouse,Clothing,28,Maryland,M,Red,Spring,NaN,Yes,Store Pickup,Yes,Yes,39,Debit Card,Bi-Weekly
80,81,19,Male,Sandals,Footwear,72,New York,XL,Blue,Summer,NaN,Yes,Store Pickup,Yes,Yes,24,Credit Card,Every 3 Months
96,97,32,Male,Gloves,Accessories,73,Delaware,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,43,Venmo,Every 3 Months
262,263,37,Male,Pants,Clothing,40,Hawaii,M,Teal,Summer,NaN,Yes,Next Day Air,Yes,Yes,6,Debit Card,Annually
330,331,46,Male,Sweater,Clothing,51,North Dakota,M,Beige,Winter,NaN,Yes,Express,Yes,Yes,43,Venmo,Bi-Weekly
356,357,56,Male,Pants,Clothing,80,Nevada,L,Black,Spring,NaN,Yes,Standard,Yes,Yes,27,Cash,Weekly
383,384,50,Male,Sunglasses,Accessories,77,West Virginia,S,Magenta,Fall,NaN,Yes,Standard,Yes,Yes,6,PayPal,Quarterly
419,420,53,Male,Shorts,Clothing,91,Utah,S,Teal,Winter,NaN,Yes,Free Shipping,Yes,Yes,14,Credit Card,Every 3 Months
442,443,29,Male,Sunglasses,Accessories,69,Michigan,M,Olive,Fall,NaN,Yes,Store Pickup,Yes,Yes,31,Credit Card,Quarterly
452,453,45,Male,Pants,Clothing,45,Missouri,M,Violet,Summer,NaN,Yes,Express,Yes,Yes,39,PayPal,Fortnightly
460,461,64,Male,Shoes,Footwear,65,South Carolina,L,Teal,Summer,NaN,Yes,Store Pickup,Yes,Yes,27,Bank Transfer,Weekly
491,492,49,Male,Coat,Outerwear,69,Vermont,M,Silver,Summer,NaN,Yes,2-Day Shipping,Yes,Yes,24,Credit Card,Bi-Weekly
512,513,19,Male,Gloves,Accessories,49,New York,L,Peach,Winter,NaN,Yes,Next Day Air,Yes,Yes,2,Bank Transfer,Monthly
560,561,25,Male,Jewelry,Accessories,48,Louisiana,L,Red,Fall,NaN,Yes,Free Shipping,Yes,Yes,12,Debit Card,Annually
628,629,69,Male,Sweater,Clothing,85,Massachusetts,M,White,Fall,NaN,Yes,2-Day Shipping,Yes,Yes,29,Credit Card,Monthly
799,800,55,Male,Belt,Accessories,55,Nevada,L,Brown,Summer,NaN,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
829,830,42,Male,Socks,Clothing,57,Idaho,S,Silver,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,14,Credit Card,Fortnightly
861,862,46,Male,Skirt,Clothing,100,Virginia,XL,Green,Spring,NaN,Yes,2-Day Shipping,Yes,Yes,35,Credit Card,Every 3 Months
888,889,49,Male,Scarf,Accessories,77,New Hampshire,S,Gold,Spring,NaN,Yes,Express,Yes,Yes,44,Cash,Annually
1072,1073,48,Male,Shorts,Clothing,92,Idaho,L,Gold,Fall,NaN,No,Express,Yes,Yes,34,Debit Card,Fortnightly
1109,1110,66,Male,Hoodie,Clothing,97,Oklahoma,L,Violet,Winter,NaN,No,Next Day Air,Yes,Yes,2,Venmo,Weekly
1124,1125,42,Male,Sweater,Clothing,20,Iowa,M,Orange,Spring,NaN,No,Express,Yes,Yes,40,Cash,Quarterly
1134,1135,62,Male,T-shirt,Clothing,81,Wisconsin,M,Brown,Summer,NaN,No,Express,Yes,Yes,2,Venmo,Every 3 Months
1151,1152,41,Male,Blouse,Clothing,86,Ohio,M,Gray,Spring,NaN,No,Express,Yes,Yes,24,Credit Card,Weekly
1176,1177,36,Male,Dress,Clothing,83,Oregon,M,Red,Winter,NaN,No,Free Shipping,Yes,Yes,39,PayPal,Quarterly
1189,1190,64,Male,Shirt,Clothing,97,Arkansas,XL,Teal,Summer,NaN,No,Free Shipping,Yes,Yes,28,Debit Card,Annually
1208,1209,20,Male,Boots,Footwear,100,Wisconsin,S,Red,Winter,NaN,No,2-Day Shipping,Yes,Yes,8,Debit Card,Annually
1220,1221,67,Male,Gloves,Accessories,64,Kentucky,M,Green,Winter,NaN,No,Express,Yes,Yes,36,Bank Transfer,Quarterly
1230,1231,25,Male,Hat,Accessories,80,Illinois,L,Brown,Spring,NaN,No,Standard,Yes,Yes,49,Venmo,Monthly
1247,1248,65,Male,T-shirt,Clothing,99,Virginia,M,Charcoal,Spring,NaN,No,Express,Yes,Yes,18,Venmo,Bi-Weekly
1292,1293,26,Male,Belt,Accessories,61,Kentucky,M,Maroon,Summer,NaN,No,Free Shipping,Yes,Yes,42,Bank Transfer,Annually
1313,1314,70,Male,Shoes,Footwear,28,Missouri,M,Lavender,Summer,NaN,No,Free Shipping,Yes,Yes,23,Credit Card,Bi-Weekly
1326,1327,40,Male,Shoes,Footwear,50,Texas,M,Indigo,Spring,NaN,No,Free Shipping,Yes,Yes,17,Cash,Monthly
1334,1335,46,Male,Coat,Outerwear,52,West Virginia,S,White,Spring,NaN,No,Store Pickup,Yes,Yes,12,Venmo,Monthly
1341,1342,26,Male,Hoodie,Clothing,27,Rhode Island,XL,Yellow,Fall,NaN,No,Standard,Yes,Yes,31,Bank Transfer,Quarterly
1370,1371,27,Male,Scarf,Accessories,67,Montana,L,Peach,Summer,NaN,No,2-Day Shipping,Yes,Yes,41,Bank Transfer,Every 3 Months

In [ ]:
df['Review Rating'] = df['Review Rating'].groupby(df['Category']).transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [ ]:
maps = {
    'Fortnightly' : 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(maps)
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [ ]:
df['purchase_frequency_days'].value_counts()

purchase_frequency_days
90     1147
14     1089
365     572
30      553
7       539
Name: count, dtype: int64

In [ ]:
df[['discount_applied', 'promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [ ]:
df.drop(columns= {'promo_code_used'})

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-aged,90

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [ ]:
from google.colab import files

In [ ]:
df.to_csv('customer_shopping_behavior_cleaned.csv', index=False)
files.download('customer_shopping_behavior_cleaned.csv')

In [ ]:
df2 = pd.read_csv('customer_shopping_behavior_cleaned.csv')

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  promo_code_used          3900 non-null   object
 15  previous_purchases       3900 non-null   int64
 16  payment_method           3900 non-null   object
 17  frequency_of_purchases   3900 non-null   object
 18  age_group                3900 non-null   object
 19  purchase_frequency_days  3900 non-null   int64
dtypes: float64(1), int64(5), object(14)
memory usage: 609.5+ KB